spring:
  profiles:
    active: dev
  session:
    store-type: redis
  redis:
    host: 108.108.108.205
    port: 6379

com:
  cloudpioneer:
    #是否改变响应状态码
    changeWebCode: true


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false