server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql://108.108.108.205:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver